### ISSUE TITLE
Create a Class (8)

### ISSUE THREAD

**Issue by jonathanmcdaniel** [mentii/mentii#10]
| Story Points | 8 |
| :-- | --- |
| **Owner** | Alex |
#### Description
As a teacher I would like to create a new class with details such as a name and a description.

#### Acceptance Criteria
- A class should be created within the system with the given details
- Both name and description must have a value

**Comment by RyanYoung25** [comment]
This consists of: 

Service for creating class entries in the DB
API Endpoint for creating class entries in the DB
Check that authorized user is a teacher
