### ISSUE TITLE
Update Auth Error Toast Message (1)

### ISSUE THREAD

**Issue by jonathanmcdaniel** [mentii/mentii#100]
Story Points | 1
:--- | --- 
**Owner** | Aaron

#### Description
As a user I would like the error message that shows when authentication fails to say "Mentii did not recognize that combination of email and password"

#### Acceptance Criteria
Authentication error toast is updated to the above string

**Comment by asp78** [comment]
Tested it out, too long of a message to read in the toast time (not for me, but prolly for someone). How about "Unrecognized email or password."

**Comment by jonathanmcdaniel** [comment]
I think thats fine
