### ISSUE TITLE
Dev and Prod Environments (5)

### ISSUE THREAD

**Issue by jonathanmcdaniel** [mentii/mentii#113]
Story Points | 5
:--- | --- 
**Owner** | Alex

#### Description
As a developer I would like a test environment that I can deploy to on aws for testing before I deploy to our prod server.

#### Acceptance Criteria
- The test environment is the default deploy target unless otherwise specified in the build script.
- The test environment mirrors the prod environment  as closely as possible

**Comment by RyanYoung25** [comment]
Duplicate
