### ISSUE TITLE
Clean up logging of exceptions in MentiiAuth (1) 

### ISSUE THREAD

**Issue by jonathanmcdaniel** [mentii/mentii#115]
Story Points | 1
:--- | --- 
**Owner** | Ryan

#### Description
As a developer I would like the exception logging of MentiiAuth cleaned up and corrected. When MentiiAuth catches something bad properly, it should probably be a warning not and error or exception. This may not mean removing the exceptions but just how we log them.

#### Acceptance Criteria
- BadSignature and Signature Expired are no longer logged as exceptions

**Comment by aaronmsegal** [comment]
Not merged yet
