### ISSUE TITLE
Class List Item Component (5)

### ISSUE THREAD

**Issue by jonathanmcdaniel** [mentii/mentii#129]
Story Points | 5
:--- | --- 
**Owner** | Jon

#### Description
As a developer I would like to create a reusable component that I can use to represent a class in a list throughout the application.

#### Acceptance Criteria
- Uses the same design as the teacher list
- is a component
- can be reused

**Comment by aaronmsegal** [comment]
Could this be more general, for use in lists of users and/or lists of activities? Or do we need a component for each of these?

**Comment by jonathanmcdaniel** [comment]
I would have to look into it but I believe it would be best to keep them separate for both semantics and styling. Each list item for those different cases will be pretty different so the view for each of these components will need to handle pretty different data and be able to style them differently. I think having these different cases built into a single component named something general is dirtier than having specifically named list item components styled for each of these cases.
