### ISSUE TITLE
View Class Details (5)

### ISSUE THREAD

**Issue by jonathanmcdaniel** [mentii/mentii#19]
| Story Points | 5 |
| :-- | --- |
| **Owner** | Alex |
#### Description

As a user I would like to be able to view a page with the details of any class that is available to me. This page should have a button to join the class.
  
#### Acceptance Criteria
- User cannot see details of private classes they are not members of
- User should be able to see the details for the class

**Comment by smc395** [comment]
To clarify, what kind of details are we showing in the class details? I'm assuming class title, section, description. Also instructor name?

**Comment by jonathanmcdaniel** [comment]
@smc395 We aren't capturing instructor name anywhere but there may be value in showing the instructor's email

**Comment by smc395** [comment]
In the backend we need to write a function to return data from the classes table. However, I don't think it make sense that every time the user clicks on a class a REST call is made to get the data. Thoughts on having the data somehow cached and then poll for the new class list every once in a while to get new classes created by teachers?

**Comment by aaronmsegal** [comment]
Micah made a good point about what details should be displayed. My current plan:

Title
Department (optional)
Section (optional)
Description
Activity List
Student List (only viewable class's teacher)
