### ISSUE TITLE
User Registration (5)

### ISSUE THREAD

**Issue by asp78** [mentii/mentii#2]
| Story Points | 5 |
| :-- | --- |
| **Owner** | Alex |
#### Description

As a user I would like to register an account for use in the system.
#### Acceptance Criteria
- Validate that the entered input is in an email address format
- Should send a confirmation email with a link which must be clicked before account is activated
- Password should be at least 8 characters long and will be entered twice to confirm
- The email that is entered does not already correspond to an existing account.
- Password should be encrypted
- Hash the password in the DB

**Comment by smc395** [comment]
- Setting up the database
- defining schema for database
- figuring out how to send email from the system to a user
- making sure we have encryption going for all parts of communication

**Comment by jonathanmcdaniel** [comment]
We also have to do the initial configuration for Flask and Angular since this will be the first implementation story

**Comment by RyanYoung25** [comment]
Vague points of the story:
- What to do if the user tries to create an account when they have an email in the system but it isn't activated yet. 
- What kind of error pages we should see
- Actually making errors respond with an error not just 200 for everything

**Comment by RyanYoung25** [comment]
User registration has been reviewed, tested, and merged. You can register a user using the Frontend and it successfully calls the backend REST calls. The vague points have been resolved.
