### ISSUE TITLE
Long emails do not work well with the Remove Student link (2)

### ISSUE THREAD

**Issue by asp78** [mentii/mentii#203]
Story Points | 2
:--- | --- 
**Owner** | Alex

#### Description
As a teacher, students with long email addresses push the **Remove Student** link off the panel

#### Acceptance Criteria
- Long emails do not move the remove student link

**Comment by smc395** [comment]
Just remove the "remove student" words next to the 'x' and put a blurb above it saying "To remove a student click the 'x' by their name' - Alex
