### ISSUE TITLE
Activity Management (13)

### ISSUE THREAD

**Issue by RyanYoung25** [mentii/mentii#23]
| Story Points | 13 |
| :-- | --- |
| **Owner** | Micah |
#### Description

As a teacher I would like to organize sections of books into activities that students can work on. Each activity may have a target date, can be locked or unlocked, and have completion criteria. 
Involves:

- Button to add an activity to description page when you are teaching the class
- Shown books available and sections available from those books
   - Select the sections to use in this activity
   - State number of problems from section
- Optionally ~due date~ Target date

#### Acceptance Criteria
- Capability to add/remove sections in activities that are associated with the class. 
- Activities cannot be locked and unlocked at the same time.

**Comment by smc395** [comment]
This story can be broken up into several smaller stories I believe. Could be a lot for one person to do this all considering finals week is coming up. Alternative option could be to do during dev week.
