### ISSUE TITLE
Pick a step and change it (8)

### ISSUE THREAD

**Issue by RyanYoung25** [mentii/mentii#28]
| Story Points | 8 |
| :-- | --- |
| **Owner** | Aaron |
#### Description

As a student, when working on a problem, I would like to be able to select a step from the displayed path of steps and then go on to input a new value for that step when I press the button that there is an incorrect step. 

If I input a bad value or a value at the wrong location I should be told that I am wrong and the last correct step should be shown. 

If the step I enter exactly matches the correct step the system knows it should perform that step and move forward one step. 

#### Acceptance Criteria

- The student must be able to select a previous step
- There needs to be an interface to allow entering a new step

**Comment by smc395** [comment]
An idea for UI flow: 
Keep the component for display problem as is (for now). That is the logic behind identifying an incorrect/correct step. If the user identifies the incorrect step by clicking on the "Incorrect Step" button, a new Angular component that handles editing a step is swapped for the display problem step component.

User can go back, which brings back the display problem component (maybe), or click some sort of submit changes button that checks what the student edited against the correct step string in the problem tree. If they edit it correctly, they move on down the problem tree. If not a toast displays incorrect correction prompt.

**Comment by jonathanmcdaniel** [comment]
merged to 11 sprint
