### ISSUE TITLE
Handle Corrected Step (13)

### ISSUE THREAD

**Issue by RyanYoung25** [mentii/mentii#29]
| Story Points | 13 |
| :-- | --- |
| **Owner** | Ryan |
#### Description

As a developer I would like to have a given 'corrected step' checked to see if it exists in the given problem data structure. 

#### Acceptance Criteria

- Whether or not the 'corrected step' is contained in the tree is returned.

**Comment by jonathanmcdaniel** [comment]
Not needed with mathsteps
