### ISSUE TITLE
Change User Privileges (5)

### ISSUE THREAD

**Issue by aaronmsegal** [mentii/mentii#3]
| Story Points | 5 |
| :-- | --- |
| **Owner** | Aaron |
#### Description

As a system administrator I want to be able to change the user privileges for other users.
#### Acceptance Criteria
-Only users with Admin privileges can access this functionality
-Users with emails listed on the teacher privileges list will have teacher privileges (create + manage class)
-Users with emails listed on the Admin Privileges list will have admin privileges

**Comment by smc395** [comment]
When you change a user to a teacher, you need to add an empty teaching list to their user object
