### ISSUE TITLE
Button to go back to class after completing problem (1)

### ISSUE THREAD

**Issue by RyanYoung25** [mentii/mentii#30]
| Story Points | 1 |
| :-- | --- |
| **Owner** | Ryan |
#### Description

As as student I want Button to go back to class after completing a problem.

#### Acceptance Criteria

- A Button that sends you back to the correct class detail page

**Comment by smc395** [comment]
Must clarify what _"giving feedback on the correctness of the answer"_ looks like. I'm imagining for this story that when the last step is presented, a person has two buttons to pick that one leads to "Uh Oh, looks like something went wrong" or "You completed the problem"
