### ISSUE TITLE
Git Tutorial

### ISSUE THREAD

**Issue by smc395** [mentii/mentii#32]
| Story Points | 3 |
| :-- | --- |
| **Owner** | Ryan |
#### Description

As a developer I would like to learn how to use git and walk through an example with other developers. 
#### Acceptance Criteria
-  Developers can complete a walk through tutorial of git

**Comment by RyanYoung25** [comment]
I'm going to make a wiki page that describes the general flow and hopefully contains some command line templates that you can copy, fill in and run. Once I make this we can go over it together and go through an example.

**Comment by aaronmsegal** [comment]
We all walked through Ryan's tutorials and know how to use git and when to ask for help
