### ISSUE TITLE
AWS Setup

### ISSUE THREAD

**Issue by smc395** [mentii/mentii#33]
| Story Points | 5 |
| :-- | --- |
| **Owner** | Jon |
#### Description

As a developer I would like to be able to setup Amazon Web Service environment for my team to use.
#### Acceptance Criteria

Amazon Web Service environment is up and running

**Comment by RyanYoung25** [comment]
Can you make a document in the wiki explaining how to access the AWS stuff and any other information you think we might need?

**Comment by RyanYoung25** [comment]
AWS is up and running, we can go to the website and use code that we have written.
