### ISSUE TITLE
Solve a problem (System Perspective) (13)

### ISSUE THREAD

**Issue by RyanYoung25** [mentii/mentii#38]
Story Points | 13
:--- | --- 
**Owner** | Ryan

#### Description
As a developer I would like the system to generate a problem solution data structure that contains paths that lead to the correct solution, paths that lead to erroneous solutions, and guidance point that the system should use to go off the correct path. 

#### Acceptance Criteria
- The data structure must be small enough to send over the network. 
- The data structure must have at least one path that leads to the correct answer. 
- All paths lead to concrete answers

**Comment by jonathanmcdaniel** [comment]
Not needed with mathsteps
