### ISSUE TITLE
Sign In (8)

### ISSUE THREAD

**Issue by RyanYoung25** [mentii/mentii#4]
| Story Points | 8 |
| :-- | --- |
| **Owner** | Micah |
#### Description

As a user I would like sign in to the system with the email address and password my account is associated with. 
#### Acceptance Criteria
- User is only signed in when they are authenticated
- A user is authenticated when their credentials match with an activated user in our system. 
- Password is stored and sent in an encrypted format
- Authenticated rest calls will then using a Basic Auth header where the username is the token and the password can be anything (unused).
- Successful authentication creates an auth token using TimedJSONWebSignatureSerializer from the itsdangerous package.
- Authentication will be tested by passing the JWT to the backend which will be decoded and printed for verification

https://blog.miguelgrinberg.com/post/restful-authentication-with-flask

**Comment by RyanYoung25** [comment]
Handle user authentication across different pages. How does it work across different components? Do we need a REST call for the authentication? What is really involved?

**Comment by aaronmsegal** [comment]
approved and merged, closing.
