### ISSUE TITLE
Standard response JSON format (2)

### ISSUE THREAD

**Issue by smc395** [mentii/mentii#44]
Story Points | 2
:--- | --- 
**Owner** | Micah

#### Description
As a developer I would like to discuss and decide on a standard JSON format for responses

https://developer.github.com/v3/users/
http://www.flaskapi.org/api-guide/status-codes/

#### What it involves:

- Building a class in python to build this json string for us
- Updating all calls to use the class and return the appropriate JSON
- Return proper status code from REST call

#### Acceptance Criteria
- All members on the team agree to the proposed format 
- On success on failure for a REST call it returns a JSON string in the agreed format.

**Comment by jonathanmcdaniel** [comment]
https://github.com/mentii/mentii/wiki/JSON-Response-Template

**Comment by RyanYoung25** [comment]
We need to think about how to get errors while we are working though things on the backend. This decision will dictate some things about how we write functions that handle the REST processing in the future. 

Ideas: 
- Simple exception handling with errors
- Returning tuples everywhere, (Data, isError)
