### ISSUE TITLE
Fix the 2 broken Backed DB related unit tests (2)

### ISSUE THREAD

**Issue by aaronmsegal** [mentii/mentii#45]
Story Points | 2
:--- | --- 
**Owner** | Micah

#### Description
In test_user_ctrl, test_isEmailInSystem(self) and test_activate(self) are not working and have been commented out. 

One needs a mock email the other is a mystery. 

#### Acceptance Criteria
Functionality should be tested properly and both tests should run successfully .

**Comment by asp78** [comment]
Comment for later remembrance, functionality around register process should be retested, as the check for if the email was in the db wasn't working properly

**Comment by asp78** [comment]
Comment for later remembrance, we need to put in an option for not actually sending emails during register since unit tests hit that code

**Comment by aaronmsegal** [comment]
If we want to always send an email, we can mock the email object for testing

**Comment by aaronmsegal** [comment]
This has been merged, closing.
