### ISSUE TITLE
html email for registration/activation link (3)

### ISSUE THREAD

**Issue by aaronmsegal** [mentii/mentii#53]
Story Points | 3
:--- | --- 
**Owner** | Micah

#### Description
The email sent during user registration with the activation link should be a html email formatted to follow the visual design of the. Clean up the page on prod when an activation link is clicked. 

#### Acceptance Criteria
After registering a new account the user receives an email formatted to follow the visual design of the website which displays properly in the gmail web client on a chromebook.
The link should reflect the environment in which it is running.

**Comment by jonathanmcdaniel** [comment]
http://foundation.zurb.com/emails.html should be useful for this. There are a few templates that we could easily modify. Additionally we can actually create a page in the frontend that just pushed the data to the appropriate endpoint instead of going to an api page directly like we are going now

**Comment by jonathanmcdaniel** [comment]
Also can you make sure that the registration endpoint no longer returns the activation id in the json response
