### ISSUE TITLE
Registration complete form wipes too soon (1)

### ISSUE THREAD

**Issue by RyanYoung25** [mentii/mentii#54]
Story Points | 1
:--- | --- 
**Owner** | Aaron

#### Description
Currently on the front end, after submitting the data in the registration form the form clears too quickly and a message is shown before the page is changed. 

#### Acceptance Criteria
Make sure the page is changed without any errors being shown to the user from clearing the form after submit is clicked. 

#### How to fix
Add a delay before wiping. Wipe when we get a response from the REST call

**Comment by asp78** [comment]
This has been fixed on 3_sprint, moving to Done
