### ISSUE TITLE
Verifying Hashed Password not the regular Password

### ISSUE THREAD

**Issue by RyanYoung25** [mentii/mentii#59]
In user_control.py register, we are hashing the password and then checking if it is 8 characters long. We need to think about how we want to fix this.

**Comment by asp78** [comment]
If this was fixed in the jsonResponse branch merge, it should be moved to closed

**Comment by aaronmsegal** [comment]
@asp78 is right this was fixed with the jsonResponse merge.

**Comment by jonathanmcdaniel** [comment]
Closing the issue
