### ISSUE TITLE
Input field placeholder text clears on focus (5)

### ISSUE THREAD

**Issue by asp78** [mentii/mentii#91]
Story Points | 5
:--- | --- 
**Owner** | Alex

#### Description
Based on user testing we found that some users were unsure as to the grey temporary text and if it had to be deleted from the input fields prior to typing. As a fix, we decided to make the input fields clear on focus. 

#### Acceptance Criteria
- All input fields lose their temporary grey text on focus

**Comment by jonathanmcdaniel** [comment]
Adding an attribute directive will probably be the simplest way to do this in a clean way:
[Attribute Directive Documentation](https://angular.io/docs/ts/latest/guide/attribute-directives.html)
