### ISSUE TITLE
Simplify Algebra Problem (5)

### ISSUE THREAD

**Issue by RyanYoung25** [mentii/mentii#94]
Story Points | 5
:--- | --- 
**Owner** | Alex

#### Description
As a developer I would like to simplify an algebraic expression given a tree representation of the equation. 

#### Acceptance Criteria
- Python functions to perform simplification of an expression. 
- Simplification must be mathematically correct.

**Comment by jonathanmcdaniel** [comment]
Not needed with mathsteps
